version: '3.8'

services:
  cms:
    build:
      context: ./server/cms
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: 'file:./server/cms/keystone.db'


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
